# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-12 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(max_length=2000)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
    ]
